# This is a basic workflow to help you get started with Actions

name: test FitHub Actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: print Hello msq 
        run: echo "Hello world from test1"
  
  test2:
    runs-on: ubuntu-latest
    needs: [test1]
    steps:
      - name: print Hello msq 
        run: echo "Hello world from test2"
