# This is a basic workflow to help you get started with Actions

name: test-GitHub-Actions
env:
  app_name: "Flask"
  pkg_name: "MyTestFlaskDeployVersion${{ github.sha }}"
  
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  
  test1:
    runs-on: ubuntu-latest0
    steps:
      - name: git clone my repo
        uses: actions/checkout@v1
          
      - name: print Hello msq 
        run: echo "Hello world from test1"
        
        
      - name: exec commands
        run: |
          echo "kek Hello msq1.1"
          echo "kek Hello msq1.2"
          echo "Application name: ${{env.app_name}}"
      
      - name: list current folder
        run: ls -la
        
        
  test2:
    runs-on: ubuntu-latest
    needs: [test1]
    env:
      var1: "This is job level var1"
      var2: "This is job level var2"
      
    steps:
      - name: test job level vars
        run: |
          echo "var1 = ${{env.var1}}"
          echo "var2 = ${{env.var2}}"
      
      - name: test step level var
        run: echo "Local step var = $localStepVar"    
        env: 
          localStepVar: "Super local"    
      
      - name: print Hello msq 
        run: echo "Hello world from test2"
      
      - name: deployment pkg
        run: |
          echo "kek Hello msq2.1"
          echo "kek Hello msq2.2"
          echo "Application name: ${{env.pkg_name}}"
      
      - name: test aws pkg 
        run: aws --version
       
      - name: test zip pkg
        run: zip --version
